// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVOqm2RjCokn1aAgXs85hxupmyVWNA-cQ',
    appId: '1:640036381047:web:13ba29c6b5c7ba260b8172',
    messagingSenderId: '640036381047',
    projectId: 'imageupdatedb',
    authDomain: 'imageupdatedb.firebaseapp.com',
    storageBucket: 'imageupdatedb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc_pWzDCAx7Gjp_y2HvpIkDZCNsO9HI-U',
    appId: '1:640036381047:android:35449f9a8c669b750b8172',
    messagingSenderId: '640036381047',
    projectId: 'imageupdatedb',
    storageBucket: 'imageupdatedb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApVxXWey3CjBdN7guslAQYHYzU-PQjpPI',
    appId: '1:640036381047:ios:149b6c8ff784fd420b8172',
    messagingSenderId: '640036381047',
    projectId: 'imageupdatedb',
    storageBucket: 'imageupdatedb.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApVxXWey3CjBdN7guslAQYHYzU-PQjpPI',
    appId: '1:640036381047:ios:149b6c8ff784fd420b8172',
    messagingSenderId: '640036381047',
    projectId: 'imageupdatedb',
    storageBucket: 'imageupdatedb.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVOqm2RjCokn1aAgXs85hxupmyVWNA-cQ',
    appId: '1:640036381047:web:134dddb2f07bb9280b8172',
    messagingSenderId: '640036381047',
    projectId: 'imageupdatedb',
    authDomain: 'imageupdatedb.firebaseapp.com',
    storageBucket: 'imageupdatedb.appspot.com',
  );
}
